#!/bin/sh
set -e

while IFS= read -r LINE; do
	FIRST=$(echo "$LINE" | cut -c 1)
	if [ '#' = $FIRST ]; then
		echo "IGNORED: $LINE"
	else
		for ITEM in $LINE; do
			echo "--> rise: $ITEM"
		done
	fi
done < $1
