#!/bin/sh
set -e

make tinyconfig


echo "\n[PROCESS LIST]"
while IFS= read -r LINE; do
	FIRST=$(echo "$LINE" | cut -c 1)
	if [ '#' = $FIRST ]; then
		true
	else
		echo "--> apply: -$LINE"
		./scripts/config $LINE
	fi
done < $1
